### ISSUE TITLE
Data Viz Video Slide

### ISSUE THREAD

**Issue by hschafer** [cse163/book#62]
Seems to be missing from our port over 

Maybe check for other video slides too?

**Comment by LuckyQXW** [comment]
I moved the data viz video to the Jupyter Notebook slide to consolidate them if that’s the one you are referring to.

**Comment by hschafer** [comment]
[This one](https://cse163.github.io/book/module-4-libraries-for-data-science/lesson-10-data-visualization/data-visualization/DataViz.html)? I don't see it there.

 I wasn't clear in the original issue, but I was referring to the "Principles of Data visualization" video.

**Comment by LuckyQXW** [comment]
Ah I think I made a mistake on that slide. Originally I didn’t notice that the Jupyter Notebook slide has video so I took the one from principles of data viz including the link to the presentation, but later I must have switched back the video from the original Jupyter Notebook lesson but forget about the principle of data viz video. You can add back the slide!
