### ISSUE TITLE
Lesson 11: Machine Learning Code confusions

### ISSUE THREAD

**Issue by jeffstride** [cse163/book#67]
In the lesson, it says: 
"Now, let’s load in this dataset and train a machine learning model to predict the species from the features!"
Error/Suggestion:
I believe that we want to predict the "city" in this lesson.

In the lesson, it says:
"In the last slide, we introduced two questions we have to ask ourselves when applying an ML task."
Error/Suggestion:
There is no previous slide, there is a previous lesson. But, the previous lesson doesn't talk about the two questions posed here, at least not that I could find. Perhaps just say, "We need to ask ourselves two questions when applying an ML task."

**Comment by hschafer** [comment]
Fixed the first one.

The second one is correct, I believe. There is an [Introduction](https://cse163.github.io/book/module-4-libraries-for-data-science/lesson-11-machine-learning/introduction.html) slide before the [Machine Learning Code](https://cse163.github.io/book/module-4-libraries-for-data-science/lesson-11-machine-learning/machine-learning-code/MachineLearning.html) slide. The questions on the previous slide are listed there but are formatted in a bit of a confusing way. I think this change will help it out a bit!
