### ISSUE TITLE
Pandas not available in executable textbook code cells

### ISSUE THREAD

**Issue by debbieyuster** [cse163/book#78]
This may be a limitation of the platform, but the cells in the Pandas lessons cannot be executed on the textbook pages because pandas is not installed. For example, on this page: [https://cse163.github.io/book/module-3-pandas/lesson-9-time-series/time-series.html](https://cse163.github.io/book/module-3-pandas/lesson-9-time-series/time-series.html)

**Comment by hschafer** [comment]
I removed the ability to run snippets since that was an integration we were trialing that is now deprecated.
